# Generated by Django 5.2.15 on 2026-07-17 09:41

import django.core.validators
import django.db.models.deletion
import navapp.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legal_name', models.CharField(max_length=255)),
                ('display_name', models.CharField(max_length=255)),
                ('short_code', models.SlugField(max_length=30, unique=True)),
                ('structure', models.CharField(max_length=255)),
                ('domicile', models.CharField(max_length=120)),
                ('year_end_month', models.PositiveSmallIntegerField(default=12, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('year_end_day', models.PositiveSmallIntegerField(default=31, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)])),
                ('report_language', models.CharField(default='en', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('investment_objective', models.TextField()),
                ('performance_note', models.TextField(blank=True)),
                ('use_org_professional_statement', models.BooleanField(default=True)),
                ('professional_investor_statement_override', models.CharField(blank=True, max_length=300)),
                ('use_org_date_statement', models.BooleanField(default=True)),
                ('date_statement_override', models.CharField(blank=True, max_length=300)),
                ('use_org_disclaimer', models.BooleanField(default=True)),
                ('disclaimer_override', models.TextField(blank=True)),
                ('disclaimer_version_override', models.CharField(blank=True, max_length=50)),
                ('disclaimer_effective_date_override', models.DateField(blank=True, null=True)),
                ('logo_override', models.ImageField(blank=True, upload_to='funds/logos/')),
                ('brand_colour_override', models.CharField(blank=True, max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9A-Fa-f]{6}$', 'Use a six-digit hex colour.')])),
                ('header_text_override', models.CharField(blank=True, max_length=300)),
                ('custom_docx_template', models.FileField(blank=True, upload_to='funds/templates/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['display_name'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(default='NAV Quarterly Reporting', max_length=200)),
                ('default_logo', models.ImageField(blank=True, upload_to='organization/')),
                ('primary_brand_colour', models.CharField(default='#183B73', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9A-Fa-f]{6}$', 'Use a six-digit hex colour.')])),
                ('professional_investor_statement', models.CharField(default='For Professional Investors only', max_length=300)),
                ('report_date_statement_template', models.CharField(default='All data as on {report_date} unless stated otherwise', max_length=300)),
                ('default_disclaimer', models.TextField(default='This document is prepared for informational purposes only.')),
                ('disclaimer_version', models.CharField(default='1.0', max_length=50)),
                ('disclaimer_effective_date', models.DateField(blank=True, null=True)),
                ('default_contact_information', models.TextField(blank=True)),
                ('percentage_decimal_places', models.PositiveSmallIntegerField(default=2)),
                ('sharpe_decimal_places', models.PositiveSmallIntegerField(default=3)),
                ('report_language', models.CharField(default='en', max_length=10)),
                ('rfr_provider', models.CharField(choices=[('FRED_DGS10', 'FRED DGS10'), ('TREASURY_CMT10', 'U.S. Treasury CMT 10-Year'), ('MANUAL', 'Manual override')], default='FRED_DGS10', max_length=30)),
                ('rfr_series', models.CharField(default='DGS10', max_length=50)),
                ('nav_change_warning_threshold', models.DecimalField(decimal_places=6, default=Decimal('0.25'), max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'organization settings',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=80)),
                ('address', models.TextField(blank=True)),
                ('display_in_report', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='navapp.fund')),
            ],
            options={
                'ordering': ['sort_order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='FundParty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party_type', models.CharField(choices=[('PORTFOLIO_MANAGER', 'Portfolio Manager'), ('GENERAL_PARTNER', 'General Partner'), ('INVESTMENT_MANAGER', 'Investment Manager'), ('ADMINISTRATOR', 'Fund Administrator'), ('AUDITOR', 'Auditor'), ('LEGAL_ADVISER', 'Legal Adviser'), ('CUSTODIAN', 'Custodian / Prime Broker'), ('OTHER', 'Other')], max_length=40)),
                ('display_label', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=255)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parties', to='navapp.fund')),
            ],
            options={
                'ordering': ['sort_order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='FundStrategyHighlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strategy_highlights', to='navapp.fund')),
            ],
            options={
                'ordering': ['sort_order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='QuarterlyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('quarter', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('version', models.PositiveIntegerField(default=1)),
                ('report_date', models.DateField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('READY', 'Ready'), ('FINAL', 'Final'), ('STALE', 'Stale / Regeneration Required'), ('GENERATION_FAILED', 'Generation failed')], default='DRAFT', max_length=30)),
                ('commentary_title', models.CharField(blank=True, max_length=200)),
                ('commentary_markdown', models.TextField(blank=True)),
                ('commentary_author', models.CharField(blank=True, max_length=150)),
                ('commentary_date', models.DateField(blank=True, null=True)),
                ('formula_version', models.CharField(default='legacy_excel_v1', max_length=50)),
                ('snapshot', models.JSONField(blank=True, default=dict)),
                ('generation_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reports_created', to=settings.AUTH_USER_MODEL)),
                ('finalized_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reports_finalized', to=settings.AUTH_USER_MODEL)),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='navapp.fund')),
            ],
            options={
                'ordering': ['-year', '-quarter', '-version'],
            },
        ),
        migrations.CreateModel(
            name='RFRObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=30)),
                ('series', models.CharField(max_length=50)),
                ('observation_date', models.DateField()),
                ('value_percent', models.DecimalField(decimal_places=8, max_digits=12)),
                ('fetched_at', models.DateTimeField()),
                ('raw_checksum', models.CharField(max_length=64)),
            ],
            options={
                'ordering': ['observation_date'],
                'indexes': [models.Index(fields=['provider', 'series', 'observation_date'], name='navapp_rfro_provide_48154e_idx')],
                'constraints': [models.UniqueConstraint(fields=('provider', 'series', 'observation_date'), name='unique_rfr_observation')],
            },
        ),
        migrations.CreateModel(
            name='RFRSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=30)),
                ('series', models.CharField(max_length=50)),
                ('annual_value_decimal', models.DecimalField(decimal_places=12, max_digits=16)),
                ('is_manual', models.BooleanField(default=False)),
                ('override_reason', models.TextField(blank=True)),
                ('override_at', models.DateTimeField(blank=True, null=True)),
                ('raw_checksum', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('override_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rfr_snapshot', to='navapp.quarterlyreport')),
            ],
        ),
        migrations.CreateModel(
            name='ShareClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('code', models.SlugField(max_length=40)),
                ('inception_date', models.DateField()),
                ('inception_nav', models.DecimalField(decimal_places=12, max_digits=30, validators=[django.core.validators.MinValueValidator(Decimal('1E-12'))])),
                ('currency', models.CharField(max_length=3)),
                ('return_basis', models.CharField(choices=[('NET', 'Net'), ('GROSS', 'Gross')], default='NET', max_length=10)),
                ('management_fee_override', models.CharField(blank=True, max_length=100)),
                ('performance_fee_override', models.CharField(blank=True, max_length=100)),
                ('bloomberg_code_override', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('display_in_quarterly_report', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='share_classes', to='navapp.fund')),
            ],
            options={
                'ordering': ['fund__display_name', 'name'],
            },
        ),
        migrations.AddField(
            model_name='quarterlyreport',
            name='share_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='navapp.shareclass'),
        ),
        migrations.CreateModel(
            name='NAVRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valuation_month', models.DateField(validators=[navapp.models.validate_month_end])),
                ('valuation_date', models.DateField()),
                ('nav_per_share', models.DecimalField(decimal_places=12, max_digits=30, validators=[django.core.validators.MinValueValidator(Decimal('1E-12'))])),
                ('status', models.CharField(choices=[('OFFICIAL', 'Official'), ('INDICATIVE', 'Indicative')], default='OFFICIAL', max_length=12)),
                ('note', models.TextField(blank=True)),
                ('raw_source_date', models.CharField(blank=True, max_length=100)),
                ('source_sheet', models.CharField(blank=True, max_length=150)),
                ('source_cell', models.CharField(blank=True, max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('change_acknowledged', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='nav_records_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='nav_records_updated', to=settings.AUTH_USER_MODEL)),
                ('share_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nav_records', to='navapp.shareclass')),
            ],
            options={
                'ordering': ['share_class', 'valuation_month'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(max_length=100)),
                ('entity_id', models.CharField(max_length=100)),
                ('action', models.CharField(max_length=100)),
                ('before_json', models.JSONField(blank=True, default=dict)),
                ('after_json', models.JSONField(blank=True, default=dict)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['entity_type', 'entity_id', 'created_at'], name='navapp_audi_entity__525366_idx')],
            },
        ),
        migrations.CreateModel(
            name='FundTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=60)),
                ('display_label', models.CharField(max_length=100)),
                ('value_text', models.CharField(max_length=255)),
                ('display_in_report', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='navapp.fund')),
            ],
            options={
                'ordering': ['sort_order', 'pk'],
                'constraints': [models.UniqueConstraint(fields=('fund', 'key'), name='unique_fund_term_key')],
            },
        ),
        migrations.CreateModel(
            name='GeneratedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(choices=[('DOCX', 'Word document'), ('PDF', 'PDF document')], max_length=10)),
                ('storage_path', models.CharField(max_length=500)),
                ('sha256', models.CharField(max_length=64)),
                ('size', models.PositiveBigIntegerField()),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='files', to='navapp.quarterlyreport')),
            ],
            options={
                'ordering': ['file_type'],
                'constraints': [models.UniqueConstraint(fields=('report', 'file_type'), name='unique_report_file_type')],
            },
        ),
        migrations.CreateModel(
            name='ReportRFRObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField()),
                ('observation_date', models.DateField()),
                ('value_percent', models.DecimalField(decimal_places=8, max_digits=12)),
                ('source_observation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='navapp.rfrobservation')),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='navapp.rfrsnapshot')),
            ],
            options={
                'ordering': ['position'],
                'constraints': [models.UniqueConstraint(fields=('snapshot', 'position'), name='unique_rfr_snapshot_position'), models.UniqueConstraint(fields=('snapshot', 'observation_date'), name='unique_rfr_snapshot_date')],
            },
        ),
        migrations.AddConstraint(
            model_name='shareclass',
            constraint=models.UniqueConstraint(fields=('fund', 'code'), name='unique_share_class_code'),
        ),
        migrations.AddIndex(
            model_name='quarterlyreport',
            index=models.Index(fields=['share_class', 'year', 'quarter', 'status'], name='navapp_quar_share_c_53d5bd_idx'),
        ),
        migrations.AddConstraint(
            model_name='quarterlyreport',
            constraint=models.UniqueConstraint(fields=('share_class', 'year', 'quarter', 'version'), name='unique_report_version'),
        ),
        migrations.AddIndex(
            model_name='navrecord',
            index=models.Index(fields=['share_class', 'valuation_month'], name='navapp_navr_share_c_b54074_idx'),
        ),
        migrations.AddConstraint(
            model_name='navrecord',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('share_class', 'valuation_month'), name='unique_active_nav_month'),
        ),
    ]
