# Generated by Django 5.2.15 on 2026-07-17 10:01

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navrecord',
            name='nav_per_share',
            field=models.DecimalField(decimal_places=18, max_digits=38, validators=[django.core.validators.MinValueValidator(Decimal('1E-18'))]),
        ),
        migrations.AlterField(
            model_name='shareclass',
            name='inception_nav',
            field=models.DecimalField(decimal_places=18, max_digits=38, validators=[django.core.validators.MinValueValidator(Decimal('1E-18'))]),
        ),
    ]
