# Generated by Django 5.2.15 on 2026-07-17 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navapp', '0002_alter_navrecord_nav_per_share_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rfrsnapshot',
            name='annual_value_decimal',
            field=models.DecimalField(decimal_places=18, max_digits=24),
        ),
    ]
