# Generated by Django 5.2.15 on 2026-07-20 03:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navapp', '0003_alter_rfrsnapshot_annual_value_decimal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fund',
            name='brand_colour_override',
            field=models.CharField(blank=True, max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9A-Fa-f]{6}$', '請輸入六位數的十六進位色碼。')]),
        ),
        migrations.AlterField(
            model_name='organizationsettings',
            name='primary_brand_colour',
            field=models.CharField(default='#183B73', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9A-Fa-f]{6}$', '請輸入六位數的十六進位色碼。')]),
        ),
    ]
