# Generated by Django 5.2.15 on 2026-07-22 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navapp', '0005_report_period_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='quarterlyreport',
            name='report_language',
            field=models.CharField(choices=[('zh-Hant', '繁體中文'), ('zh-Hans', '簡體中文')], default='zh-Hant', max_length=10),
        ),
    ]
